### PR TITLE
Feature/link outfit card to object

### PR DESCRIPTION
**Pull request by lmanriq**
# Description

Please include a summary of the change.  
I used local storage to store new outfits when they are saved. I then created an accessOutfits function that uses the innertext of the event.target to pull the corresponding outfit from the local storage object. The function then loops through that object's garments and shows any saved garments as visible. 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the Turing style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by edlsto** [comment]
Hi,

This looks great. I tested it out and the functionality works well. Nice work!

My main concerns with this implementation would be:

• Local storage not clearing out. If you use the site for a while, the local storage would get loaded up with lots and lots of saved outfits that are never cleared.

• Name conflicts. If you name the two different saved outfits the same thing such as "beach bear", it overwrites the old version.

• Duplicate/redundant storage. If we're storing all the saved outfits in the outfits array, can we just access them from there, instead of also storing them as separate key/value pairs within the localStorage object?

My thoughts are: This works, lets merge it. We can come back and refactor later to address the above.

**Comment by lmanriq** [comment]
Hey Ed, 

Thanks for your thoughts! Yes, after submitting this and upon further reflection, it seems like it will be a better idea to make sure the storage and deletion of our outfit cards works first. Then we can make sure that this functionality still works and integrate it at that point.

**Comment by edlsto** [comment]
Sounds good. I'm glad we talked about this.

**Comment by lmanriq** [comment]
Hi Ed, 

We updated this together. So we remember, we went back in and updated it so that now we are using the functionality we implemented for saving outfit cards to also access saved object instances from our local storage. Now when you click on the names within teh saved outfit cards, that outfit loads. The functionality remains on page load.

**Comment by edlsto** [comment]
Yay!

**Pull request merged**
